#include<bits/stdc++.h>
using namespace std;
int n;
int t[200];
//判断密码安全度
//先判定有没有字母、数字、特殊字符
//对于高安全度要判定同一个字符有没有出现两次
// int judge(string &s){
//     int len=s.length();
//     for(int i=0;i<len;i++){
//         t[s[i]]++;
//     }
//     for(int i=;i<len;i++){
//         if()
//     }
// }
int main(){
    cin>>n;
    string s;
    for(int i=1;i<=n;i++){
        cin>>s;
    }
    char f=91;
    cout<<f;
}

int a='a';
int z='z';
int A='A';
int Z='Z';
int x='#';
int y='*';
int w='0';
int e='9';
char f=91;